image: node:lts-bullseye-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'staging'
    - if: $CI_COMMIT_BRANCH == 'aws'

default:
  cache:
    key: 
      prefix: $CI_COMMIT_REF_SLUG
      files:
        - server/package-lock.json
        - client/package-lock.json
    paths:
      - server/.npm/
      - client/.npm/
  before_script:
    - cd server && npm ci --cache .npm --prefer-offline && cd ../client && npm ci --cache .npm --prefer-offline && cd ..

stages:
  - lint
  - build
  - test
  - size-check
  - deploy


# Lint job for server
lint-server:
  stage: lint
  script:
    - cd server 
    - npx eslint
  allow_failure: false

# Lint job for client
lint-client:
  stage: lint
  script:
    - cd client
    - npx eslint

# Test job for server
test-server:
  stage: test
  script:
    - cd server
    - npm run test

# Build job for client
build-client:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 day
  only:
    refs:
      - main
      - staging
      - aws

# Size check 
bundlesize-check:
  stage: size-check
  dependencies:
    - build-client
  script:
    - cd client
    - npm run bundlesize
  allow_failure: false
  only:
    refs:
      - main
      - staging
      - aws


# make artifact for aws deployment
aws-artifact:
  stage: deploy
  dependencies:
    - build-client
  only: 
    - tag
  script:
    - tar -czvf 520-project-hussain-tran-holmes.tar.gz README.md client/dist package-lock.json package.json  planning/ screenshot.png  server/
  artifacts:
      paths:
        - ./520-project-hussain-tran-holmes.tar.gz
      expire_in: 7 days

