image: node:lts-bullseye-slim

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'staging'

default:
  cache:
    key: 
      prefix: $CI_COMMIT_REF_SLUG
      files:
        - server/package-lock.json
        - client/package-lock.json
    paths:
      - server/.npm/
      - client/.npm/
  before_script:
    - cd server && npm ci --cache .npm --prefer-offline && cd ../client && npm ci --cache .npm --prefer-offline && cd ..

stages:
  - lint
  - build
  - test

# Lint job for server
lint-server:
  stage: lint
  script:
    - cd server 
    - npx eslint
  allow_failure: false

# Lint job for client
lint-client:
  stage: lint
  script:
    - cd client
    - npx eslint

# Test job for server
test-server:
  stage: test
  script:
    - cd server
    - npm run test

# Build job for client
build-client:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - client/dist/
    expire_in: 1 day
  only:
    refs:
      - main
      - staging
